/**
 * MAIN OPERATIONS — ARIA ONE-TIME TEAM INTRODUCTION MESSAGE (Phase 4, Goal B)
 *
 * Fixed, pre-approved content. Deliberately NOT generated by the AI
 * provider — per the Phase 4 spec, this is fixed wording and calling the
 * AI provider for it would only add cost, latency, and wording drift.
 *
 * This file only builds the message content. The one-time send gate lives
 * in the route handler (src/app/api/aria/team-intro/send/route.ts), never
 * here.
 */

const SUBJECT = "Alpha Brooks Energy — ARIA Daily Team Report Starting Tomorrow";

const BODY_TEXT = `Good morning Team,

Starting tomorrow, ARIA will provide the daily team work report every morning based on the tasks assigned to each person in Planner.

Please keep your Planner tasks updated during the day. For anything blocked, add a short note beginning with:

BLOCKER:

ARIA is currently waiting for the remaining team members to have their tasks assigned so everyone can be included in the daily report.

Thank you.
ARIA
Alpha Brooks Energy LTD`;

function escapeHtml(text: string): string {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function textToHtml(text: string): string {
  return text
    .split("\n\n")
    .map((paragraph) => `<p style="margin:0 0 12px 0;">${escapeHtml(paragraph).replace(/\n/g, "<br/>")}</p>`)
    .join("");
}

export interface TeamIntroContent {
  subject: string;
  bodyHtml: string;
  bodyText: string;
}

/** Fixed, approved wording — never passed through the AI provider. */
export function getTeamIntroContent(): TeamIntroContent {
  return {
    subject: SUBJECT,
    bodyHtml: `<div style="font-family:Segoe UI,Arial,sans-serif;font-size:14px;line-height:1.5;color:#1a1a1a;">${textToHtml(
      BODY_TEXT
    )}</div>`,
    bodyText: BODY_TEXT,
  };
}